@echo off
setlocal
title Kvest Nablyudatelya - Local Server

REM Открываем браузер на 2 секунды позже, чтобы сервер успел подняться.
start "" /B cmd /c "timeout /t 2 /nobreak >nul & start """" http://localhost:5544/"

REM Запускаем встроенный PowerShell HTTP-сервер (без Node/Python)
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root=Split-Path -Parent $MyInvocation.MyCommand.Path; if(-not $root){$root=(Get-Location).Path}; $root=(Resolve-Path %~dp0).Path; $listener=New-Object Net.HttpListener; $listener.Prefixes.Add('http://localhost:5544/'); try { $listener.Start() } catch { Write-Host ('Failed to start: ' + $_.Exception.Message) -ForegroundColor Red; Read-Host 'Press Enter to exit'; exit 1 }; Write-Host ('Server up: http://localhost:5544/  (root: ' + $root + ')') -ForegroundColor Green; $mime=@{'.html'='text/html; charset=utf-8'; '.htm'='text/html; charset=utf-8'; '.js'='application/javascript; charset=utf-8'; '.mjs'='application/javascript; charset=utf-8'; '.css'='text/css; charset=utf-8'; '.png'='image/png'; '.jpg'='image/jpeg'; '.jpeg'='image/jpeg'; '.gif'='image/gif'; '.webp'='image/webp'; '.svg'='image/svg+xml'; '.json'='application/json; charset=utf-8'; '.ico'='image/x-icon'; '.txt'='text/plain; charset=utf-8'; '.md'='text/plain; charset=utf-8'; '.ttf'='font/ttf'; '.otf'='font/otf'; '.woff'='font/woff'; '.woff2'='font/woff2' }; while($listener.IsListening){ try { $ctx=$listener.GetContext(); $req=$ctx.Request; $res=$ctx.Response; $path=[Uri]::UnescapeDataString($req.Url.AbsolutePath); if($path -eq '/' -or $path -eq ''){ $path='/index.html' }; $full=Join-Path $root ($path.TrimStart('/').Replace('/', [IO.Path]::DirectorySeparatorChar)); if([IO.File]::Exists($full)){ $bytes=[IO.File]::ReadAllBytes($full); $ext=[IO.Path]::GetExtension($full).ToLower(); $ct=$mime[$ext]; if(-not $ct){ $ct='application/octet-stream' }; $res.ContentType=$ct; $res.Headers.Add('Cache-Control','no-store'); $res.ContentLength64=$bytes.Length; $res.OutputStream.Write($bytes,0,$bytes.Length); Write-Host ('  200 ' + $path) -ForegroundColor Gray } else { $res.StatusCode=404; $msg=[Text.Encoding]::UTF8.GetBytes('Not found: ' + $path); $res.OutputStream.Write($msg,0,$msg.Length); Write-Host ('  404 ' + $path) -ForegroundColor Yellow }; $res.Close() } catch { Write-Host ('  err ' + $_.Exception.Message) -ForegroundColor Red } }"
endlocal
